CREATE DATABASE [SQLOpsDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SQLOpsDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SQLOpsDB.mdf' , SIZE = 262144KB , FILEGROWTH = 262144KB )
 LOG ON 
( NAME = N'SQLOpsDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SQLOpsDB_log.ldf' , SIZE = 262144KB , FILEGROWTH = 262144KB )
GO
ALTER DATABASE [SQLOpsDB] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [SQLOpsDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SQLOpsDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SQLOpsDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SQLOpsDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SQLOpsDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [SQLOpsDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SQLOpsDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SQLOpsDB] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [SQLOpsDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SQLOpsDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SQLOpsDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SQLOpsDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SQLOpsDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SQLOpsDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SQLOpsDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SQLOpsDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SQLOpsDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SQLOpsDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SQLOpsDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SQLOpsDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SQLOpsDB] SET  READ_WRITE 
GO
ALTER DATABASE [SQLOpsDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SQLOpsDB] SET  MULTI_USER 
GO
ALTER DATABASE [SQLOpsDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SQLOpsDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SQLOpsDB] SET DELAYED_DURABILITY = DISABLED 
GO
USE [SQLOpsDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [SQLOpsDB]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [SQLOpsDB] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
