USE [SQLOpsDB]
GO

CREATE TABLE dbo.SQLErrorLog_Stats
 (ID INT IDENTITY(1,1) PRIMARY KEY,
  SQLInstanceID INT NOT NULL,
  LastDateTimeCaptured DATETIME DEFAULT('1900-01-01 00:00:00'))

CREATE INDEX idx_SQLErrorLog_Stats_SQLInstanceID ON dbo.SQLErrorLog_Stats(SQLInstanceID)
GO