USE [SQLOpsDB]
GO

/****** Object:  Table [dbo].[ExtendedProperty]    Script Date: 10/31/2022 6:02:42 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ExtendedProperty](
	[ExtendedPropertyID] [int] IDENTITY(1,1) NOT NULL,
	[ExtendedPropertyName] [varchar](255) NOT NULL,
 CONSTRAINT [PK_ExtendedProperty] PRIMARY KEY CLUSTERED 
(
	[ExtendedPropertyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


