USE [SQLOpsDB]
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Logs
	DROP CONSTRAINT DF_Logs_DateTimeCaptured
GO
CREATE TABLE dbo.Tmp_Logs
	(
	LogID bigint NOT NULL IDENTITY (1, 1),
	DateTimeCaptured datetime NOT NULL,
	ProcessID int NOT NULL,
	Description varchar(512) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_Logs SET (LOCK_ESCALATION = TABLE)
GO
ALTER TABLE dbo.Tmp_Logs ADD CONSTRAINT
	DF_Logs_DateTimeCaptured DEFAULT (getdate()) FOR DateTimeCaptured
GO
ALTER TABLE dbo.Tmp_Logs ADD CONSTRAINT
	DF_Logs_ProcessID DEFAULT -1 FOR ProcessID
GO
SET IDENTITY_INSERT dbo.Tmp_Logs ON
GO
IF EXISTS(SELECT * FROM dbo.Logs)
	 EXEC('INSERT INTO dbo.Tmp_Logs (LogID, DateTimeCaptured, Description)
		SELECT LogID, DateTimeCaptured, Description FROM dbo.Logs WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_Logs OFF
GO
DROP TABLE dbo.Logs
GO
EXECUTE sp_rename N'dbo.Tmp_Logs', N'Logs', 'OBJECT' 
GO
ALTER TABLE dbo.Logs ADD CONSTRAINT
	PK_Logs PRIMARY KEY CLUSTERED 
	(
	LogID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
COMMIT
